# Generated by Django 3.1.1 on 2020-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_blog_myname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reemail',
            field=models.EmailField(default='', max_length=40),
        ),
    ]
